name: Build

"on":
  "push":
    "tags":
      - "v*"
    "branches":
      - "*"
  "pull_request":

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Prepare environment
        run: |-
          RELEASE_VERSION="${GITHUB_REF##*/}"
          if [[ "${RELEASE_VERSION}" != v* ]]; then RELEASE_VERSION='dev'; fi
          echo "RELEASE_VERSION=\"${RELEASE_VERSION}@${GITHUB_SHA:0:10}\"" | tee -a $GITHUB_ENV
          go mod vendor
          go generate -x

      # Win
      - run: GOOS=windows GOARCH=386 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=windows GOARCH=amd64 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=windows GOARCH=amd64 GOAMD64=v3 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=windows GOARCH=arm64 VERSION=${RELEASE_VERSION} make release

      # MacOS
      - run: GOOS=darwin GOARCH=amd64 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=darwin GOARCH=arm64 VERSION=${RELEASE_VERSION} make release

      # Linux X86/AMD64
      - run: GOOS=linux GOARCH=386 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=linux GOARCH=amd64 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=linux GOARCH=amd64 GOAMD64=v3 VERSION=${RELEASE_VERSION} make release

      # Linux ARM
      - run: GOOS=linux GOARCH=arm GOARM=6 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=linux GOARCH=arm64 VERSION=${RELEASE_VERSION} make release

      # Linux MIPS/MIPSLE
      - run: GOOS=linux GOARCH=mips GOMIPS=softfloat VERSION=${RELEASE_VERSION} make release
      - run: GOOS=linux GOARCH=mipsle GOMIPS=softfloat VERSION=${RELEASE_VERSION} make release

      # FreeBSD X86
      - run: GOOS=freebsd GOARCH=386 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=freebsd GOARCH=amd64 VERSION=${RELEASE_VERSION} make release

      # FreeBSD ARM/ARM64
      - run: GOOS=freebsd GOARCH=arm GOARM=6 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=freebsd GOARCH=arm64 VERSION=${RELEASE_VERSION} make release

      - run: ls -l build/aiodns-*

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/aiodns-*"
          token: ${{ secrets.GITHUB_TOKEN }}
